### ISSUE TITLE
여러 Ingress에 대해 하나의 ALB를 활용하는, AWS IngressGroup에 대응되는 기능이 있나요?

### ISSUE THREAD

**Issue by a3626a** [NaverCloudPlatform/nks-alb-ingress-controller#25]
안녕하세요.

`nks-alb-ingress-controller` 를 활용하여 2개 이상의 Ingress를 k8s 상에 생성하면, ALB 인스턴스가 그 개수만큼 생성됩니다.
이 경우 결국 DNS 레벨에서 다시 domain을 기반으로 ALB로 라우팅을 해야하므로 Ingress의 장점을 크게 퇴색시키게 됩니다.
즉 ALB를 사용하는 이유가 HTTP 에 기반한 (host, path) 라우팅 기능이 있기 때문인데, Ingress 마다 ALB를 만들어버리면 추가적인 라우팅 레이어가 필요합니다.

aws-load-balancer-controller는 [Ingress Group](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#ingressgroup)이라는 개념을 도입하여 여러 Ingress를 하나의 ALB 인스턴스로 처리할 수 있도록 기능을 제공하고 있습니다.

nks-alb-ingress-controller에서도 비슷한 기능이 있는 지 찾아보고 있는데 `alb.ingress.kubernetes.io/conditions` 및 `alb.ingress.kubernetes.io/actions` 가 가장 가능성이 있으나 이것으로 원하는 구성이 가능할 것 같진 않습니다.

Ingress Group 기능이 없이는 nks-alb-ingress-controller가 굉장히 제한적인 환경에서만 활용할 수 있고 일반적인 운영 환경에서는 활용이 어려운 도구라고 생각이 되는데요. (nginx-ingress-controller에 대한 비교 우위가 떨어집니다) 혹시 현재 이 기능이 갖춰져 있거나, 개발 계획이 있을까요?

**Comment by Jaeyo** [comment]
@a3626a 안그래도 IngressGroup 개념을 도입하는 태스크가 백로그에 있긴 한데 아직 진행하지 못하고 있습니다.
공수가 꽤 들 것으로 예상되는 태스크라 올해 안으로는 어려울 것 같고 내년 목표로 진행하려고 합니다.

**Comment by a3626a** [comment]
> @a3626a 안그래도 IngressGroup 개념을 도입하는 태스크가 백로그에 있긴 한데 아직 진행하지 못하고 있습니다. 공수가 꽤 들 것으로 예상되는 태스크라 올해 안으로는 어려울 것 같고 내년 목표로 진행하려고 합니다.

답변 감사드립니다. Ingress Group 개발 완료되면 그 때라도 alb-ingress-controller 적극 활용해보도록 하겠습니다. 감사합니다.
